### ISSUE TITLE
Document initial design

### ISSUE THREAD

**Issue by alanbover** [kube-trail/kube-trail#1]
Let's discuss here (or in google groups) the initial design

**Comment by ivanilves** [comment]
Let's start from discussing the value this could provide to users and listing some typical use cases.

And then decide what things we would implement in scope of MVP, limit the scope as narrow as we could (quien mucho abarca poco aprieta), and then open a shared G-doc to discuss WHAT?/WHY?/HOW?/etc!

**Comment by Fsero** [comment]
It is complex to design from scratch the whole idea so lets do it by pieces.

First we should set the goal *WHAT* is the problem set we want to address and *WHY*. If we agree on those two we can start about the HOW.

For me, kubernetes is a great piece of technology specially if you are an ops inclined developer you can understand why your pods are failing and you can retrieve from the kubernetes API the errors, however doing that is time consuming and error prone since there are several places where you need to look at. My _service_ is not running could mean:

1. I have a typo on my ingress rule.
2. My image cannot be pulled from the container registry.
3. The resources i have assigned to my pod exceeds the quota.
4. The HPA couldn't get metrics and didnt scale the number of replicas of my deployment.
5. The credentials assigned to your deployment does not grant access to secrets needed on the pod.
6. . . .

You need to have a deep understand about all the pieces involved maintaining your service up and running  on a kubernetes cluster. The main goal of kube-trail is to help development of services pointing out errors and _recommending_ settings to existing services.

GOALS:

* Expose developers about common pitfalls in their deployments, ingress rule...
* Recommend best practices for performance and security in some API objects like deployments (set resources,enable prometheus scraping if there is a prometheus installed) or ingress rules.

**Comment by Fsero** [comment]
@alanbover @zmalik @ivanilves @zonzamas @sergi WDYT

**Comment by alanbover** [comment]
Completelly agree with Fabian description. To summarize it (IMO):

What?
Non-technical kubernetes users suffers a lot debugging issues when running in the cluster. Meanwhile there is a lot of tooling helping non-technical users to deploy, there is almost nothing about 
troubleshooting and visualization.

Why?
Kubernetes is composed by many pieces that can be swapped for others. This creates an environment with many moving pieces hard to debug, even more with limited access. The fact that the pieces can be changed for others makes almost every Kubernetes setup unique.

How?
Create a system to unify and enrich events from multiple API objects / components that will help users or external services to visualize and hook on certain issues / problems. This system needs to be pluggable, so the logic can be extended for each component added into the cluster.
